surface.CreateFont( "infoXLarge", {
   font = "Trebuchet24",
   extended = false,
   size = 40,
   weight = 600,
   blursize = 0,
   scanlines = 0,
   antialias = true,
   underline = false,
   italic = false,
   strikeout = false,
   symbol = false,
   rotary = false,
   shadow = false,
   additive = false,
   outline = false,
} )

surface.CreateFont( "infoLarge", {
   font = "Trebuchet24",
   extended = false,
   size = 23,
   weight = 530,
   blursize = 0,
   scanlines = 0,
   antialias = true,
   underline = false,
   italic = false,
   strikeout = false,
   symbol = false,
   rotary = false,
   shadow = false,
   additive = false,
   outline = false,
} )

surface.CreateFont( "infoSmall", {
   font = "Trebuchet24",
   extended = false,
   size = 17,
   weight = 530,
   blursize = 0,
   scanlines = 0,
   antialias = true,
   underline = false,
   italic = false,
   strikeout = false,
   symbol = false,
   rotary = false,
   shadow = false,
   additive = false,
   outline = false,
} )